# Generated by Django 4.1 on 2025-12-30 10:53

from django.db import migrations, models
import musician.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=63)),
                ('last_name', models.CharField(max_length=63)),
                ('instrument', models.CharField(max_length=63)),
                ('age', models.PositiveIntegerField(validators=[musician.models.age_validator])),
                ('date_of_applying', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
